// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sniffer/v1/processor.proto

// Wire contract between the node-local collector (DaemonSet) and the central
// processor (Deployment). Collector and processor roll independently, so this
// schema must only evolve additively: never renumber or reuse a field.

package snifferv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the node the collector runs on (downward API).
	NodeName      string        `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Records       []*FlowRecord `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_sniffer_v1_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sniffer_v1_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_sniffer_v1_processor_proto_rawDescGZIP(), []int{0}
}

func (x *ReportRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ReportRequest) GetRecords() []*FlowRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_sniffer_v1_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sniffer_v1_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_sniffer_v1_processor_proto_rawDescGZIP(), []int{1}
}

// FlowRecord is a canonical (caller -> callee) connection observation,
// aggregated on the node over a short window. The caller's ephemeral port is
// dropped so connection churn collapses into one record with a count.
type FlowRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 4 or 16 byte addresses.
	SrcIp []byte `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp []byte `protobuf:"bytes,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	// Callee listening port.
	DstPort uint32 `protobuf:"varint,3,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	// IANA protocol number (6 = TCP).
	Protocol uint32 `protobuf:"varint,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// True when captured on the connecting side, false on the accepting side.
	Outbound bool `protobuf:"varint,5,opt,name=outbound,proto3" json:"outbound,omitempty"`
	// Pod UID of the connecting process, resolved on the node from its cgroup.
	// Empty when unknown (accepted side, host process, or exited process).
	SrcPodUid string `protobuf:"bytes,6,opt,name=src_pod_uid,json=srcPodUid,proto3" json:"src_pod_uid,omitempty"`
	// Command name of the connecting process; empty on the accepted side.
	Comm string `protobuf:"bytes,7,opt,name=comm,proto3" json:"comm,omitempty"`
	// Number of connections folded into this record.
	Count             uint32 `protobuf:"varint,8,opt,name=count,proto3" json:"count,omitempty"`
	FirstSeenUnixNano int64  `protobuf:"varint,9,opt,name=first_seen_unix_nano,json=firstSeenUnixNano,proto3" json:"first_seen_unix_nano,omitempty"`
	LastSeenUnixNano  int64  `protobuf:"varint,10,opt,name=last_seen_unix_nano,json=lastSeenUnixNano,proto3" json:"last_seen_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FlowRecord) Reset() {
	*x = FlowRecord{}
	mi := &file_sniffer_v1_processor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowRecord) ProtoMessage() {}

func (x *FlowRecord) ProtoReflect() protoreflect.Message {
	mi := &file_sniffer_v1_processor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowRecord.ProtoReflect.Descriptor instead.
func (*FlowRecord) Descriptor() ([]byte, []int) {
	return file_sniffer_v1_processor_proto_rawDescGZIP(), []int{2}
}

func (x *FlowRecord) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *FlowRecord) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *FlowRecord) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *FlowRecord) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *FlowRecord) GetOutbound() bool {
	if x != nil {
		return x.Outbound
	}
	return false
}

func (x *FlowRecord) GetSrcPodUid() string {
	if x != nil {
		return x.SrcPodUid
	}
	return ""
}

func (x *FlowRecord) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *FlowRecord) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FlowRecord) GetFirstSeenUnixNano() int64 {
	if x != nil {
		return x.FirstSeenUnixNano
	}
	return 0
}

func (x *FlowRecord) GetLastSeenUnixNano() int64 {
	if x != nil {
		return x.LastSeenUnixNano
	}
	return 0
}

var File_sniffer_v1_processor_proto protoreflect.FileDescriptor

const file_sniffer_v1_processor_proto_rawDesc = "" +
	"\n" +
	"\x1asniffer/v1/processor.proto\x12\n" +
	"sniffer.v1\"^\n" +
	"\rReportRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x120\n" +
	"\arecords\x18\x02 \x03(\v2\x16.sniffer.v1.FlowRecordR\arecords\"\x10\n" +
	"\x0eReportResponse\"\xb7\x02\n" +
	"\n" +
	"FlowRecord\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\fR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\fR\x05dstIp\x12\x19\n" +
	"\bdst_port\x18\x03 \x01(\rR\adstPort\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\rR\bprotocol\x12\x1a\n" +
	"\boutbound\x18\x05 \x01(\bR\boutbound\x12\x1e\n" +
	"\vsrc_pod_uid\x18\x06 \x01(\tR\tsrcPodUid\x12\x12\n" +
	"\x04comm\x18\a \x01(\tR\x04comm\x12\x14\n" +
	"\x05count\x18\b \x01(\rR\x05count\x12/\n" +
	"\x14first_seen_unix_nano\x18\t \x01(\x03R\x11firstSeenUnixNano\x12-\n" +
	"\x13last_seen_unix_nano\x18\n" +
	" \x01(\x03R\x10lastSeenUnixNano2S\n" +
	"\x10ProcessorService\x12?\n" +
	"\x06Report\x12\x19.sniffer.v1.ReportRequest\x1a\x1a.sniffer.v1.ReportResponseB?Z=github.com/ecojuntak/network-sniffer/api/sniffer/v1;snifferv1b\x06proto3"

var (
	file_sniffer_v1_processor_proto_rawDescOnce sync.Once
	file_sniffer_v1_processor_proto_rawDescData []byte
)

func file_sniffer_v1_processor_proto_rawDescGZIP() []byte {
	file_sniffer_v1_processor_proto_rawDescOnce.Do(func() {
		file_sniffer_v1_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sniffer_v1_processor_proto_rawDesc), len(file_sniffer_v1_processor_proto_rawDesc)))
	})
	return file_sniffer_v1_processor_proto_rawDescData
}

var file_sniffer_v1_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sniffer_v1_processor_proto_goTypes = []any{
	(*ReportRequest)(nil),  // 0: sniffer.v1.ReportRequest
	(*ReportResponse)(nil), // 1: sniffer.v1.ReportResponse
	(*FlowRecord)(nil),     // 2: sniffer.v1.FlowRecord
}
var file_sniffer_v1_processor_proto_depIdxs = []int32{
	2, // 0: sniffer.v1.ReportRequest.records:type_name -> sniffer.v1.FlowRecord
	0, // 1: sniffer.v1.ProcessorService.Report:input_type -> sniffer.v1.ReportRequest
	1, // 2: sniffer.v1.ProcessorService.Report:output_type -> sniffer.v1.ReportResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sniffer_v1_processor_proto_init() }
func file_sniffer_v1_processor_proto_init() {
	if File_sniffer_v1_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sniffer_v1_processor_proto_rawDesc), len(file_sniffer_v1_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sniffer_v1_processor_proto_goTypes,
		DependencyIndexes: file_sniffer_v1_processor_proto_depIdxs,
		MessageInfos:      file_sniffer_v1_processor_proto_msgTypes,
	}.Build()
	File_sniffer_v1_processor_proto = out.File
	file_sniffer_v1_processor_proto_goTypes = nil
	file_sniffer_v1_processor_proto_depIdxs = nil
}
